// crates/metis-docs-gui/src/components/TiptapEditor.tsx
import React from 'react';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Placeholder from '@tiptap/extension-placeholder';
import Typography from '@tiptap/extension-typography';

export interface TiptapEditorProps {
  content: string;
  onChange: (content: string) => void;
  placeholder?: string;
  className?: string;
  editable?: boolean;
}

export const TiptapEditor: React.FC<TiptapEditorProps> = ({
  content,
  onChange,
  placeholder = 'Start writing...',
  className = '',
  editable = true,
}) => {
  const editor = useEditor({
    extensions: [
      StarterKit,
      Placeholder.configure({
        placeholder,
      }),
      Typography,
    ],
    content,
    editable,
    onUpdate: ({ editor }) => {
      onChange(editor.getHTML());
    },
  });

  React.useEffect(() => {
    if (editor && content !== editor.getHTML()) {
      editor.commands.setContent(content);
    }
  }, [editor, content]);

  if (!editor) {
    return null;
  }

  return (
    <div className={`tiptap-editor ${className}`}>
      {editable && (
        <div className="tiptap-toolbar border-b border-gray-200 p-2 flex gap-2 bg-gray-50">
          <button
            onClick={() => editor.chain().focus().toggleBold().run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('bold') ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            Bold
          </button>
          <button
            onClick={() => editor.chain().focus().toggleItalic().run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('italic') ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            Italic
          </button>
          <button
            onClick={() => editor.chain().focus().toggleHeading({ level: 1 }).run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('heading', { level: 1 }) ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            H1
          </button>
          <button
            onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('heading', { level: 2 }) ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            H2
          </button>
          <button
            onClick={() => editor.chain().focus().toggleBulletList().run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('bulletList') ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            Bullet List
          </button>
          <button
            onClick={() => editor.chain().focus().toggleOrderedList().run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('orderedList') ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            Numbered List
          </button>
          <button
            onClick={() => editor.chain().focus().toggleBlockquote().run()}
            className={`px-2 py-1 rounded text-sm ${
              editor.isActive('blockquote') ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            Quote
          </button>
        </div>
      )}
      <EditorContent 
        editor={editor} 
        className="tiptap-content p-4 min-h-[400px] prose prose-sm max-w-none focus:outline-none"
      />
    </div>
  );
};

// crates/metis-docs-gui/src/components/TiptapEditor.vue
<template>
  <div class="tiptap-editor h-full flex flex-col">
    <!-- Toolbar - only show when editable -->
    <div v-if="editable" class="tiptap-toolbar border-b border-gray-200 p-2 flex gap-2 bg-gray-50">
      <button
        @click="editor?.chain().focus().toggleBold().run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('bold') 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        Bold
      </button>
      <button
        @click="editor?.chain().focus().toggleItalic().run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('italic') 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        Italic
      </button>
      <button
        @click="editor?.chain().focus().toggleHeading({ level: 1 }).run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('heading', { level: 1 }) 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        H1
      </button>
      <button
        @click="editor?.chain().focus().toggleHeading({ level: 2 }).run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('heading', { level: 2 }) 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        H2
      </button>
      <button
        @click="editor?.chain().focus().toggleBulletList().run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('bulletList') 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        Bullet List
      </button>
      <button
        @click="editor?.chain().focus().toggleOrderedList().run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('orderedList') 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        Numbered List
      </button>
      <button
        @click="editor?.chain().focus().toggleBlockquote().run()"
        :class="[
          'px-2 py-1 rounded text-sm transition-colors',
          editor?.isActive('blockquote') 
            ? 'bg-blue-600 text-white' 
            : 'bg-white text-gray-700 hover:bg-gray-100'
        ]"
      >
        Quote
      </button>
    </div>

    <!-- Editor Content -->
    <EditorContent 
      :editor="editor" 
      class="tiptap-content p-4 prose prose-sm max-w-none focus:outline-none flex-1 overflow-y-auto h-full"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onBeforeUnmount } from 'vue'
import { useEditor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import Placeholder from '@tiptap/extension-placeholder'
import { Markdown } from 'tiptap-markdown-3'
// Removed gray-matter to avoid Node.js Buffer dependency in browser

interface Props {
  content: string
  placeholder?: string
  editable?: boolean
}

interface Emits {
  (e: 'update', content: string): void
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Start writing...',
  editable: true,
})

const emit = defineEmits<Emits>()

const pendingContent = ref<string | null>(null)

// Process content to separate frontmatter from markdown
const processContent = (content: string): string => {
  try {
    // Manual frontmatter removal (browser-safe, no Node.js dependencies)
    const lines = content.split('\n')
    if (lines[0] === '---') {
      const endIndex = lines.findIndex((line, index) => index > 0 && line === '---')
      if (endIndex > 0) {
        return lines.slice(endIndex + 1).join('\n').trim()
      }
    }
    return content.trim()
  } catch (error) {
    console.error('Error parsing frontmatter:', error)
    return content.trim()
  }
}

const getMarkdown = (): string => {
  if (!editor.value) return ''
  const storage = editor.value.storage as any
  return storage.markdown?.getMarkdown() || ''
}

const editor = useEditor({
  content: '',
  extensions: [
    StarterKit.configure({
      heading: { levels: [1, 2, 3, 4, 5, 6] }
    }),
    Placeholder.configure({
      placeholder: props.placeholder,
    }),
    Markdown.configure({
      html: true,
      tightLists: true,
      bulletListMarker: '-'
    })
  ],
  onCreate: ({ editor: e }) => {
    // Load content when editor is ready
    if (props.content) {
      setTimeout(() => {
        const processedContent = processContent(props.content)
        if (e && processedContent) {
          e.commands.setContent(processedContent)
        }
      }, 50)
    }
  },
  onUpdate: () => {
    // Get markdown content from the editor
    const markdownContent = getMarkdown()
    emit('update', markdownContent)
  },
})

// Watch for content changes (new document loaded)
watch(() => props.content, (newContent) => {
  if (newContent && editor.value) {
    const processedContent = processContent(newContent)
    if (processedContent !== editor.value.getHTML()) {
      editor.value.commands.setContent(processedContent)
    }
  } else if (newContent) {
    pendingContent.value = newContent
  }
}, { immediate: false })

// Watch for editable changes
watch(() => props.editable, (newEditable) => {
  if (editor.value) {
    editor.value.setEditable(newEditable)
  }
}, { immediate: true })

onBeforeUnmount(() => {
  if (editor.value) {
    editor.value.destroy()
  }
})
</script>

<style scoped>
.tiptap-content {
  height: 100% !important;
  max-height: none !important;
  display: flex;
  flex-direction: column;
}

.tiptap-content :deep(.ProseMirror) {
  outline: none;
  height: 100% !important;
  flex: 1;
  min-height: 0;
}

.tiptap-content :deep(.ProseMirror p.is-editor-empty:first-child::before) {
  color: #adb5bd;
  content: attr(data-placeholder);
  float: left;
  height: 0;
  pointer-events: none;
}
</style>
